name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

concurrency:
  # On master/release, we don't want any jobs cancelled so the sha is used to name the group
  # On PR branches, we cancel the job if new commits are pushed
  # More info: https://stackoverflow.com/a/68422069/253468
  group: ${{ (github.ref == 'refs/heads/branch_1.2.18' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release' ) && format('ci-main-{0}', github.sha) || format('ci-main-{0}', github.ref) }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  Test:
    name: JDK ${{ matrix.jdk }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        jdk: [8]
        os: [ubuntu-latest]
      fail-fast: true
      max-parallel: 4
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Set up Java ${{ matrix.jdk }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'      
        java-version: ${{ matrix.jdk }}
        cache: maven
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package
    - name: Generate documentation
      run: mvn javadoc:aggregate


